version: '3'
services:
    # Do our routing here instead
    nginx:
        # Enable if not using network_mode: "host"
        # ports:
        #     - 80
        #     - 443
        image: nginx:alpine
        deploy:
            replicas: 1
        # Bind directly to host interface (only needed if proxy_pass uses localhost for anything)
        network_mode: "host"
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./locations:/etc/nginx/locations
            - ./sites-enabled:/etc/nginx/sites-enabled
            - ./snippets:/etc/nginx/snippets
            - ./certs:/etc/ssl/certs/site
            - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
